### ISSUE TITLE
Distribution to Firebase fails

### ISSUE THREAD

**Issue by jbuda** [guness/bitrise-step-firebase-app-distribution#12]
I can't seem to get this to work, my distribution step to Firebase is always failing with the following error : 

npm ERR! path /usr/local/bin/firebase
npm ERR! code EEXIST
npm ERR! Refusing to delete /usr/local/bin/firebase: node_modules/npm/bin/npm-cli.js symlink target is not controlled by npm /usr/local/bin
npm ERR! File exists: /usr/local/bin/firebase
npm ERR! Move it away, and try again.

Ive added a step before the distribution to delete the '/usr/local/bin/firebase' directory but it doesn't seem to make a difference. 

Any help would be appreciated.

**Comment by guness** [comment]
@jbuda which stack do you use? have you tried different stacks?

**Comment by jbuda** [comment]
Hi @guness 
The Stack used is _Xcode 11.1.x, on macOS 10.14.6 (Mojave)_

Will try the next build on a new Stack and see what happens.

**Comment by xuzhe** [comment]
Same here. It seems some stacks already have firebase installed at /local/usr/bin
I am not sure if it's a npm bug or Bitrise's problem.

**Comment by xuzhe** [comment]
@jbuda Hi, before @guness merging my pull request or Bitrise done something to their enviroment, you can simply replace `- firebase-app-distribution@0.4.0:` to `- git::https://github.com/xuzhe/bitrise-step-firebase-app-distribution.git:` (or make your own fork) in your bitrise.yml file to avoid this error.
