### ISSUE TITLE
Does not work for iOS Builds

### ISSUE THREAD

**Issue by Abdul-Hannan** [guness/bitrise-step-firebase-app-distribution#14]
Hello,

I am getting this error related to NPM

<img width="594" alt="Screen Shot 2019-11-19 at 6 32 49 PM" src="https://user-images.githubusercontent.com/7346169/69155601-7426f280-0afb-11ea-8904-0d4351eeed15.png">

the step works fine  on Android builds

**Comment by vscafuto** [comment]
Facing the same issue...

**Comment by guness** [comment]
this is known, here is the PR to fix. temporary workaround is also mentioned on the PR, until it is deployed.

**Comment by guness** [comment]
since PR is merged, closing this one. it should be available soon.
