### ISSUE TITLE
add releaseNotesFile property

### ISSUE THREAD

**Issue by frakc** [guness/bitrise-step-firebase-app-distribution#16]
Hello, can you please add releaseNotesFile, as releaseNotes field is not sufficient.

**Comment by guness** [comment]
actually you can do it via **Additional Command Flags** by passing parameter as 
`--release-notes-file "/path/to/release-notes.txt"`

**Comment by menasameh** [comment]
Hey @guness how to pass **Additional Command Flags** ?

**Comment by guness** [comment]
via `Additional Command Flags` input:
<img width="749" alt="Screen Shot 2020-01-29 at 18 09 42" src="https://user-images.githubusercontent.com/16373485/73368800-a5bdf600-42c2-11ea-8d13-27568587ede0.png">

**Comment by guness** [comment]
it has been added, and will be published on next build.

**Comment by guness** [comment]
PR is open : https://github.com/bitrise-io/bitrise-steplib/pull/2400

**Comment by guness** [comment]
should be fine now on version 0.6.0
