### ISSUE TITLE
Service Credentials File can refer to link url instead of local path

### ISSUE THREAD

**Issue by danielhalim11** [guness/bitrise-step-firebase-app-distribution#19]
Hi, following up on this request https://github.com/guness/bitrise-step-firebase-app-distribution/issues/9, I want to request the service credentials file can refer to download link url directly instead of we have to download it manually and put on local directory.
Possible reason: Someone that have "Rebuild with Remove Access" access may be able to see the file and see the credential?

**Comment by guness** [comment]
I don't think Firebase CLI itself supports direct URL to service credentials file, and can see no value implementing download mechanism within plugin. One with remote access can interfere with the flow in any step and gain access to credential file. Therefore it is not a viable solution.

Besides, purpose of the plugin is to support what Firebase App Distribution supports. So, this specific request is out of the scope.
