### ISSUE TITLE
Release notes file option not being displayed on the UI

### ISSUE THREAD

**Issue by Bunn** [guness/bitrise-step-firebase-app-distribution#20]
For some reason when I add this step into my workflow the release notes file option is not displayed on the UI.
Not sure what's causing that since the it seems to be added correctly into the yml file:
https://github.com/guness/bitrise-step-firebase-app-distribution/blob/58de8f635d14b021b5a9ce26ce33f9fc6cb20f39/step.yml#L81

Here's a screenshot of how it looks when I add the step, notice the missing release notes **file** option
<img width="300" alt="image" src="https://user-images.githubusercontent.com/782316/74610129-4b0d0280-50e8-11ea-8fac-fadaa558dbc2.png">

Thanks for taking a look at this and let me know if I can help :)

**Comment by Bunn** [comment]
Maybe the plugin version was never updated after the release notes file option was added?

I see here it says 0.5.0
https://github.com/guness/bitrise-step-firebase-app-distribution/blob/58de8f635d14b021b5a9ce26ce33f9fc6cb20f39/bitrise.yml#L9
And the last change on this file was on Nov 18, 2019

But the new option was added on Feb 5 2020
https://github.com/guness/bitrise-step-firebase-app-distribution/commit/bfd9a183326138b22f871261245868460d62a0d6#diff-91d8d269a1c9bd3631ddb04b80b01c4e

I'd guess that bumping it to 0.5.1 would do the trick. (I'm not 100% familiar on how bitrise checks for new version of community created plugins)

**Comment by guness** [comment]
@Bunn this feature is not released yet. it will be released soon.
in the mean time you can use by changing appropriate line at `bitrise.yml` to:
`- git::https://github.com/guness/bitrise-step-firebase-app-distribution.git@develop:`

**Comment by guness** [comment]
PR is open : https://github.com/bitrise-io/bitrise-steplib/pull/2400

**Comment by guness** [comment]
should be fine now on version 0.6.0

**Comment by Bunn** [comment]
@guness I can confirm it's working. Thanks :)
