### ISSUE TITLE
Fails without diagnostics if the release notes field is too large

### ISSUE THREAD

**Issue by alondero** [guness/bitrise-step-firebase-app-distribution#25]
Our distribution was failing randomly and wasn't suggesting why it was failing. 
After playing around with a few variables I noticed that the release notes were pretty long, so blanked it out for the build which subsequently passed.

Suggest that this step truncates the release notes to maybe no more than 100 characters so it passes verification

**Comment by guness** [comment]
@alondero are you sure it is not because of a single quote ?
o/w limitations are set by firebase itself, not us.

**Comment by alondero** [comment]
It is using a single quote yes, should it be double? I'm using version 0.6.0

**Comment by guness** [comment]
@alondero we have known bug about single quote, and it is fixed on 0.7.0.
however it is not yet deployed by bitrise.
https://github.com/bitrise-io/bitrise-steplib/pull/2445

**Comment by guness** [comment]
@alondero  can you retry with the last version (0.7.0)

**Comment by alondero** [comment]
It worked, thank you!
