### ISSUE TITLE
Suggestion : generate output variable

### ISSUE THREAD

**Issue by chenghuangqobuz** [guness/bitrise-step-firebase-app-distribution#26]
Hi,

Is there possible to generate output variable for url of this specify version?  I'd like to post this url link to jira, so QA can just click the url to download the right version.

Thanks

**Comment by guness** [comment]
@chenghuangqobuz direct Binary download is not available on Firebase App Distribution. However by using `Deploy to bitrise io` step you can get direct link to Binary file. Let me know if you need more help.

**Comment by chenghuangqobuz** [comment]
@guness Thanks for the response. I used bitrise io before but bitrise io can't list all versions and can't manage permissions. 

Good work for the step.

**Comment by guness** [comment]
@alexsinger if you would like to record customer feedback ^^

**Comment by alexsinger** [comment]
Thanks @guness and @chenghuangqobuz it's good feedback. Providing back a URL is something we've thought about as an improvement. I'll pass along to the team too.
