### ISSUE TITLE
App path defined but the file does not exist at path

### ISSUE THREAD

**Issue by emitchel** [guness/bitrise-step-firebase-app-distribution#27]
Configs:
    * firebase_token: [REDACTED]
    * service_credentials_file: 
    * app_path: ./app/build/outputs/apk/develop/debug
    * app: xxxxxx
    * release_notes: 
    * release_notes_file: 
    * testers: 
    * groups: Internal
    * flags: 
    * is_debug: true
    * upgrade_firebase_tools: false
    App path contains one file 👍
    App path defined but the file does not exist at path: ./app/build/outputs/apk/develop/debug

Looks like it's found the path with an .apk, but it's not finding the file. What file is it specifically looking for? Bitrise uploads the artifacts as expected, so I know it's in that directory. It's set to $BITRISE_APK_PATH

**Comment by guness** [comment]
@emitchel it is looking for absolute file path. Directory will fail as expected.

**Comment by emitchel** [comment]
So why is it failing for $BUTRISE_APK_PATH?

**Comment by guness** [comment]
@emitchel can you share the steps you are using?
we should see something like:
`app_path: /bitrise/deploy/app-debug.apk`

**Comment by emitchel** [comment]
You are correct - updating the path to the adjusted absolute path works.
