### ISSUE TITLE
Error: Failed to authenticate, have you run firebase login?

### ISSUE THREAD

**Issue by osborneomuya** [guness/bitrise-step-firebase-app-distribution#29]
I run into this error when setting up firebase app distribution on bitrise CI.I have used a script to download the firebase credentials file and a step to verify the file is downloaded.i have done everything from this answer https://github.com/guness/bitrise-step-firebase-app-distribution/issues/9
What could be causing the authentication issue?How do I run firebase login?
Here is an extract from my build:
![Screenshot_20200804-214148_Firefox](https://user-images.githubusercontent.com/12794991/89332071-70dc9280-d69b-11ea-9e87-006436f03fb4.jpg)

**Comment by guness** [comment]
it is probably not finding the service credentials file. please double check the path.

**Comment by osborneomuya** [comment]
The file exists in the path.i have a step to verify the file is downloaded and it is.if I do an ls of the directory I can see it.is there a specific way to call the service credential file once its downloaded from the download step?

**Comment by guness** [comment]
can you run build with remote access and see the content of the file is there, and firebase binary sees it.

can you also share a bit more logs, prior to the error.

**Comment by osborneomuya** [comment]
i ran build with remote access and i can see the content of the file.
 logs, prior to the error

**Comment by osborneomuya** [comment]
How do I view error logs with remote access?I could get more detail from there.

**Comment by guness** [comment]
I don't know how to access Bitrise logs on the fly but you can always check from their dashboard.
Have you tried turning debug on...
<img width="328" alt="Screen Shot 2020-08-07 at 19 03 48" src="https://user-images.githubusercontent.com/16373485/89665098-d077af80-d8e0-11ea-8ddf-7977c77fa095.png">


and can you show settings on this field
<img width="394" alt="Screen Shot 2020-08-07 at 19 03 37" src="https://user-images.githubusercontent.com/16373485/89665136-dcfc0800-d8e0-11ea-93c7-89cf04af84de.png">

**Comment by osborneomuya** [comment]
![Screenshot from 2020-08-08 10-49-18](https://user-images.githubusercontent.com/12794991/89705359-5e957980-d965-11ea-85d5-12fd2f4967eb.png)
here is the config for the firebase distributtion step.I have hidden the Firebase App ID.

**Comment by guness** [comment]
we are sure that `$FIREBASE_DISTRIBUTION_KEY_DEV` points to the file you download right?

**Comment by osborneomuya** [comment]
yes its downloaded in the download step above,there is also a script that confirms the json file is downloaded there.

**Comment by osborneomuya** [comment]
![Screenshot from 2020-08-08 11-16-59](https://user-images.githubusercontent.com/12794991/89705791-b386bf00-d968-11ea-97bf-3654e1fd23d0.png)
 an ls of the directory confirms the json file is there.

**Comment by guness** [comment]
well, everything from our end seems correct then.

can you try running `firebase projects:list` on CI server during a remote build?
there are a few options...
- Broken JSON file
- Invalid credentials (from a secondary account)
- file permissions (a very long shot)
...

I can try debugging in place if it is OK for you to share project/build. o/w you need to ask to customer support.

**Comment by osborneomuya** [comment]
i get this with debug on
"Deploying build to Firebase
  firebase appdistribution:distribute "/bitrise/deploy/app-dev-debug.apk" --app "1:347947913315:android:ed79486a949002d8" --groups "collaborators" --debug
[2020-08-08T08:23:54.805Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2020-08-08T08:23:54.823Z] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at ReadStream.<anonymous> (/root/.cache/firebase/tools/lib/node_modules/google-auth-library/build/src/auth/googleauth.js:346:39)
    at ReadStream.emit (events.js:327:22)
    at ReadStream.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Error: Failed to authenticate, have you run firebase login?"

**Comment by guness** [comment]
aha, you see. file is broken.

**Comment by osborneomuya** [comment]
I cant find where the error is could you help me identify it?

**Comment by guness** [comment]
`Unexpected token < in JSON at position 0` means file content is broken.

**Comment by osborneomuya** [comment]
Will redownloading the file fix it?

**Comment by guness** [comment]
how can I know?

**Comment by guness** [comment]
seems off-topic

**Comment by Nived660987** [comment]
firebase login --no-localhost   
try the above command in your terminal it will pop up a new window login with the same id that you used for firebase db ,once logged in it will give you a string copy that string and paste in your terminal

**Comment by ErcilioMarques** [comment]
just do firebase login on your terminal and login

**Comment by etim8832** [comment]
ใด้ยัง
