### ISSUE TITLE
App path defined but the file does not exist at path: /Users/vagrant/deploy/app-arm64-v8a-release.apk

### ISSUE THREAD

**Issue by vamsi575kg** [guness/bitrise-step-firebase-app-distribution#30]
| (7) flutter-build@0                                                          |
+------------------------------------------------------------------------------+
| id: flutter-build                                                            |
| version: 0.13.2                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-08-28T05:24:41Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- IOSAdditionalParams: --release
- AndroidAdditionalParams: --split-per-abi
- Platform: android
- IOSExportPattern: *build/ios/iphoneos/*.app
- AndroidOutputType: apk
- AndroidExportPattern: *build/app/outputs/apk/*/*.apk
*build/app/outputs/bundle/*/*.aab
- IOSCodesignIdentity: 
- ProjectLocation: /Users/vagrant/git/----
- DebugMode: true
- CacheLevel: all
- AndroidBundleExportPattern: *build/app/outputs/bundle/*/*.aab
Build Android
$ flutter "build" "apk" "--split-per-abi"
Running Gradle task 'assembleRelease'...                        
Calling mockable JAR artifact transform to create file: /Users/vagrant/.gradle/caches/transforms-2/files-2.1/9e1879314ade476d6637d20f9e9a5f48/android.jar with input /usr/local/share/android-sdk/platforms/android-28/android.jar
Calling mockable JAR artifact transform to create file: /Users/vagrant/.gradle/caches/transforms-2/files-2.1/e4cf0bff47c901202ccb24607357d606/android.jar with input /usr/local/share/android-sdk/platforms/android-29/android.jar
Removed unused resources: Binary resource data reduced from 428KB to 349KB: Removed 18%
Removed unused resources: Binary resource data reduced from 428KB to 349KB: Removed 18%
Removed unused resources: Binary resource data reduced from 428KB to 349KB: Removed 18%
Running Gradle task 'assembleRelease'...                          219.9s (!)
✓ Built build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk (13.4MB).
Export Android artifact
couldn't find output artifact on path: /Users/vagrant/git/----/*build/app/outputs/bundle/*/*.aab
- BITRISE_APK_PATH: /Users/vagrant/deploy/app-x86_64-release.apk
- BITRISE_APK_PATH_LIST: /Users/vagrant/deploy/app-arm64-v8a-release.apk|/Users/vagrant/deploy/app-armeabi-v7a-release.apk|/Users/vagrant/deploy/app-x86_64-release.apk
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | flutter-build@0                                               | 3.8 min  |
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+

| (8) deploy-to-bitrise-io@1                                                   |
+------------------------------------------------------------------------------+
| id: deploy-to-bitrise-io                                                     |
| version: 1.10.0                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-08-28T05:28:29Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- BuildURL: https://app.bitrise.io/build/2c1a8d0880ffc6ef
- APIToken: [REDACTED]
- IsCompress: false
- ZipName: 
- DeployPath: /Users/vagrant/deploy
- NotifyUserGroups: everyone
- NotifyEmailList: 
- IsPublicPageEnabled: true
- PublicInstallPageMapFormat: {{range $index, $element := .}}{{if $index}}|{{end}}{{$element.File}}=>{{$element.URL}}{{end}}
- BuildSlug: 2c1a8d0880ffc6ef
- TestDeployDir: /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/test_results381692385
- AppSlug: dfacd85283ea2db9
- AddonAPIBaseURL: [REDACTED]
- AddonAPIToken: [REDACTED]
- DebugMode: false
- BundletoolVersion: 0.13.4
Deploying the content of the Deploy directory separately
List of files to deploy
- /Users/vagrant/deploy/app-arm64-v8a-release.apk
- /Users/vagrant/deploy/app-armeabi-v7a-release.apk
- /Users/vagrant/deploy/app-x86_64-release.apk
Deploying files
Uploading apk file: /Users/vagrant/deploy/app-arm64-v8a-release.apk
analyzing apk
  apk infos: map[app_name:------- min_sdk_version:21 package_name:----- version_code:2009 version_name:1.0.0]
creating artifact
  file size: 13MB
uploading artifact
finishing artifact
Uploading apk file: /Users/vagrant/deploy/app-armeabi-v7a-release.apk
analyzing apk
  apk infos: map[app_name:----- min_sdk_version:21 package_name:----- version_code:1009 version_name:1.0.0]
creating artifact
  file size: 13MB
uploading artifact
finishing artifact
Uploading apk file: /Users/vagrant/deploy/app-x86_64-release.apk
analyzing apk
  apk infos: map[app_name:---- min_sdk_version:21 package_name:------ version_code:4009 version_name:1.0.0]
creating artifact
  file size: 14MB
uploading artifact
finishing artifact
Success

Upload test results
- uploading (0) test results
Success
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | deploy-to-bitrise-io@1                                        | 29.87 sec|
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+

| (9) firebase-app-distribution@0                                              |
+------------------------------------------------------------------------------+
| id: firebase-app-distribution                                                |
| version: 0.7.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2020-08-28T05:28:59Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Configs:
  * firebase_token: [REDACTED]
  * service_credentials_file: 
  * app_path: /Users/vagrant/deploy/app-arm64-v8a-release.apk
/Users/vagrant/deploy/app-armeabi-v7a-release.apk
/Users/vagrant/deploy/app-x86_64-release.apk
  * app: 1:211721978750:android:f3a97654bcb1ed6741e92f
  * release_notes: 
  * release_notes_file: 
  * testers: 
  * groups: ----
  * flags: 
  * is_debug: true
  * upgrade_firebase_tools: true
App path contains one file 👍
App path defined but the file does not exist at path: /Users/vagrant/deploy/app-arm64-v8a-release.apk
/Users/vagrant/deploy/app-armeabi-v7a-release.apk
/Users/vagrant/deploy/app-x86_64-release.apk
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | firebase-app-distribution@0 (exit code: 1)                    | 2.34 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...b.com/guness/bitrise-step-firebase-app-distribution/issues |
| Source: https://github.com/guness/bitrise-step-firebase-app-distribution     |
+---+---------------------------------------------------------------+----------+

**Comment by guness** [comment]
I am not sure if firebase App distribution supports Split APK. can you check if I was wrong?

**Comment by vamsi575kg** [comment]
If you manually drop all the 3 files in the Firebase beta distribution console it shows as a single version. Not sure if they have API support for uploading a list of apk's though. 

May be triggering multiple uploads can give the expected result. 
firebase appdistribution:distribute app-arm64-v8a-release.apk  \   --app 1:1234567890:android:0a1b2c3d4e5f67890  
firebase appdistribution:distribute app-armeabi-v7a-release.apk  \   --app 1:1234567890:android:0a1b2c3d4e5f67890
firebase appdistribution:distribute app-x86_64-release.apk  \   --app 1:1234567890:android:0a1b2c3d4e5f67890

**Comment by guness** [comment]
hmm, I am not seeing anything about uploading multiple files at once.

probably you need to add 3 of the steps, one step for an APK. Still, I am not sure if it split APK works on app distribution.

**Comment by guness** [comment]
closing this one, let me know if you need more help.
