### ISSUE TITLE
Why App ID is "[REDACTED]"? This issue the following error.

### ISSUE THREAD

**Issue by jhamin0511** [guness/bitrise-step-firebase-app-distribution#34]
![image](https://user-images.githubusercontent.com/23713053/106684027-fe784b00-6608-11eb-8663-42b1a79f86f5.png)

![image](https://user-images.githubusercontent.com/23713053/106684163-4303e680-6609-11eb-9275-e7597177a4d1.png)

---

This is the case that worked normally.

![image](https://user-images.githubusercontent.com/23713053/106685280-70519400-660b-11eb-959b-a961b52523b2.png)

![image](https://user-images.githubusercontent.com/23713053/106685393-a7c04080-660b-11eb-88c3-18be47973b25.png)

---

I double-checked it with the Firebase CLI.

![image](https://user-images.githubusercontent.com/23713053/106685714-4fd60980-660c-11eb-9e12-74a01576aee9.png)

![image](https://user-images.githubusercontent.com/23713053/106685835-9166b480-660c-11eb-8e7e-f5b6bff33459.png)

How to not REDACTED?? APP ID.

**Comment by guness** [comment]
[REDACTED] Means your app id is not printed to console, but it is used properly. The error however is clear on RED:

```We could not find a contact email, please visit Firebase Console for app distribution and set a contact email there.```

Let me know if this does not fix your problem. Closing right now.

**Comment by jhamin0511** [comment]
![image](https://user-images.githubusercontent.com/23713053/106822700-e8c75c00-66c2-11eb-978a-ce62bf3d1c14.png)

I definitely wrote down the contact email.

`We could not find a contact email, please visit Firebase Console for app distribution and set a contact email there. `
 I don't know why the error occurs.

Is there any other way to solve this problem?

**Comment by guness** [comment]
I have double checked my logs, it is not redacted. have you put your App ID into secrets?

**Comment by jhamin0511** [comment]
No. I entered App ID directly in the Firebase App ID field.
![image](https://user-images.githubusercontent.com/23713053/106975756-74f88280-679a-11eb-82b5-2f98586029f2.png)

**Comment by guness** [comment]
can you also  check what is defined in SECRETS tab? maybe since it was defined there as well and it just causes this redaction without we know it.
