### ISSUE TITLE
Question : Is this step support app bundle (aab) for Android

### ISSUE THREAD

**Issue by moatazeldebsy** [guness/bitrise-step-firebase-app-distribution#37]
Is this step support app bundle (aab) for Android ? or only .apk? thank you

<img width="1253" alt="Screenshot 2021-07-05 at 10 15 37" src="https://user-images.githubusercontent.com/45570191/124746429-230e8100-df21-11eb-9e0f-4654d45f277b.png">

**Comment by guness** [comment]
this is just a lack of documentation, but the step supports the bundles(aab) as well.

let me fix that quick for the documentation. but you can use current version.
