### ISSUE TITLE
The default path fails for IPA

### ISSUE THREAD

**Issue by micHar** [guness/bitrise-step-firebase-app-distribution#38]
The default value for the file path is: `$BITRISE_IPA_PATH|$BITRISE_APK_PATH|$BITRISE_AAB_PATH` (at least it was for me after the latest change to 0.9.x).

This started to fail, however, with `app_path: /Users/vagrant/deploy/abc.ipa||` and `App path contains || . You need to choose one build path: /Users/vagrant/deploy/talkmanIos.ipa||`.

I am building a kotlin multiplatform app with the same step reused to output ios and android app, so it would be great if it could work with that setup like it did before.

**Comment by guness** [comment]
@micHar have you tried on 0.9.1 ?

**Comment by guness** [comment]
it seems you are using `0.9.0`. This is fixed by `0.9.1`. Closing the issue, let me know if the problem persists.

**Comment by guness** [comment]
here is the link to fixed version: https://github.com/bitrise-io/bitrise-steplib/pull/3111
