### ISSUE TITLE
Validation in case FIREBASE_TOKEN is exported in the environment

### ISSUE THREAD

**Issue by elizedelabrida** [guness/bitrise-step-firebase-app-distribution#43]
It would be great if the script validated if **FIREBASE_TOKEN** variable is exported (not only firebase_token) and threw an error.

I had a case in Bitrise where there was a **secret env var** named exactly **FIREBASE_TOKEN**. This caused an issue while trying to authenticate with a **service account**, because even while firebase_token inside the script was empty, it was still trying to authenticate using the token:

![Captura de Tela 2021-10-19 às 15 57 08](https://user-images.githubusercontent.com/52866532/137973852-ff647e56-b859-4619-9a4a-e3e3cddb1ff3.png)

It took me a while to figure out that the problem was a secret env var named FIREBASE_TOKEN. Renaming it solved the problem.

**Comment by odemolliens** [comment]
any news? it has been a long time ago

**Comment by guness** [comment]
> any news? it has been a long time ago

Not really, but let's not wait for new features. I will put this in my TODO list ahead. Thanks for reminding me.

**Comment by guness** [comment]
I am making a change regarding this. Instead of exporting input from the field, now using this as input the firebase binary.

However firebase app distribution binary itself may read it from environment variables. this is not something we can fix for sure.

I have added a warning just in case.
