### ISSUE TITLE
Release notes length exceeds maximum character limit

### ISSUE THREAD

**Issue by imranMnts** [guness/bitrise-step-firebase-app-distribution#44]
I have this error in my build with a big release note

```Error: failed to update release notes with HTTP Error: 400, Release notes length exceeds maximum character limit```

Can it be possible to add in the readme the maximum size of the release note and/or handle the case when it appears, to crop it and succeed the step?

**Comment by guness** [comment]
Maximum size is not controlled by this plugin. Rather it is controlled by Firebase. They can just update it without giving notice. So it does not make sense to mention that is potentially inaccurate.

In addition, cropping peoples' word and calling it a success is not desirable behavior.
