### ISSUE TITLE
Both authentication methods are defined although I only use credentials file

### ISSUE THREAD

**Issue by jdanthinne** [guness/bitrise-step-firebase-app-distribution#63]
Hi,

I'm getting a strange error when using this step.
I'm only referencing a credentials file, but in the log I can see "**Both authentication methods are defined**" and the command fails.

```
Configs:
* firebase_token:
* service_credentials_file: /var/folders/71/rszmbrmd6tv4pg52z6ql_5c0000gn/T/GENERIC_FILE_STORAGE1683874599/xxxxx.json
* app_path: /Users/vagrant/deploy/xxxxxxxxe.ipall
* app: 1:xxxxxxxxxx
* release_notes:
* release_notes_length:
* release_notes_file:
* testers:
* groups: decathlon
* flags:
* is_debug: false
* upgrade_firebase_tools: false
App path ends with || . Manually fixing path: /Users/vagrant/deploy/xxxxxxxxxx.ipal|
Both authentication methods are defined: Firebase Token (via FIREBASE_TOKEN environment variable) and Service Credentials Field, one is enough.
-- Checking for existing firebase-tools on PATH...
Your machine has firebase-tools@13.4.0 installed.
If you would like to upgrade your install run: curl -sL firebase.tools | upgrade=true bash
Deploying build to Firebase
firebase appdistribution:distribute "/Users/vagrant/deploy/ConnectedLockerSample.ipa" --app
"1:xxxxxxxxx" -groups "xxxxxxxxx"
Authenticating with 'FIREBASE_TOKEN' is deprecated and will be removed in a future major version of
'firebase-tools'. Instead, use a service account key with *GOOGLE_APPLICATION_CREDENTIALS*: https://cloud.google.com/docs/authentication/getting-started
uploading binary...
Error: Failed to upload release. Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth
For CI servers and headless environments, generate a new token with firebase login:ci
```

<img width="719" alt="Capture d’écran 2024-04-29 à 10 59 16" src="https://github.com/guness/bitrise-step-firebase-app-distribution/assets/485107/16677d88-c308-44c6-a221-e4090813a8c2">

<img width="679" alt="Capture d’écran 2024-04-29 à 10 58 50" src="https://github.com/guness/bitrise-step-firebase-app-distribution/assets/485107/345bb047-9f4d-43de-b4f6-f13e465fd728">

**Comment by Landino98** [comment]
Hi, did you resolve it?

**Comment by unwmun-arooo** [comment]
You might want to check **Workflow Editor>Secrets** to make sure you don't have any variables declared with FIREBASE_TOKEN. This is a system environment variable value, so it applies even if you didn't set it in the Firebase App Distribution Step. 
Alternatively, check that nothing is set as a system environment variable in the step before it runs.

**Comment by jdanthinne** [comment]
@unwmun-arooo  Ooooh, you're right, there was a variable in the secrets… renamed it and it works fine now. Thanks!
