### ISSUE TITLE
I'm encountering an error because I'm unable to install Firebase tools.

### ISSUE THREAD

**Issue by y-hakutaku** [guness/bitrise-step-firebase-app-distribution#70]
It seems that this issue might be related, so this step may not be usable until Firebase tools address it. However, is there any workaround available?

- Related issue
https://github.com/firebase/firebase-tools/issues/7865

**Comment by guness** [comment]
There is no current workaround available, and even if we add it now, it will take some time to deploy on the Bitrise side. I am sure the Firebase guys will fix it soon. Watching the linked issue and keeping this one open until they fix it.

Thanks for pointing out.

**Comment by y-hakutaku** [comment]
@guness 

Thank you for your response.

The Firebase team has just finished their work, and it has been confirmed that everything is functioning properly on Bitrise. Therefore, I will close this issue.

- Related Comment.
https://github.com/firebase/firebase-tools/issues/7865#issuecomment-2433095692
