### ISSUE TITLE
[Feature] Customised ReadMe file based on Github Pull Request 

### ISSUE THREAD

**Issue by mamatagelanee07** [guness/bitrise-step-firebase-app-distribution#8]
For Firebase App Distribution, Is it possible to generate a customized string for the ReadMe file based on Pull Request/ Commit message [(Pull Request Template)? ](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository)

**Pros:** 
QA can understand features/changes have been made for build generated from merging Pull Request.

**Comment by mamatagelanee07** [comment]
![issue_template](https://user-images.githubusercontent.com/8694335/66749283-5f629980-ee81-11e9-92b4-a05ab92dc2cf.png)

**Comment by guness** [comment]
First of all, this step is not meant to generate resource, it is just to distribute assets. 
Secondly, git related outputs are available `Git Clone Repository` step. You can create a customized string or a file using those information and give input to Firebase App Distribution step.

<img width="338" alt="Screen Shot 2019-10-14 at 16 09 39" src="https://user-images.githubusercontent.com/16373485/66753743-16b8d980-ee9d-11e9-99cd-c42f2f344633.png">
You can create this using a Script step. or basically 
`$GIT_CLONE_COMMIT_MESSAGE_SUBJECT` or `$GIT_CLONE_COMMIT_MESSAGE_BODY` message as an input for `Release Notes` parameter. 👍

**Comment by mamatagelanee07** [comment]
After opening issue, found `$BITRISE_GIT_MESSAGE` which I can use, 

Thanks 👍
